export const Styles = [
  {
    styleName: "Kabuki",
    miracle: "Chai",
    tarot: "0 - The Fool",
    attArr: [0, 3, 3, 5, 2, 4, 2, 4],
  },
  {
    styleName: "Vasara",
    miracle: "Catastrophe",
    tarot: "1 - The Magician",
    attArr: [3, 5, 2, 5, 1, 3, 1, 3],
  },
  {
    styleName: "Tatara",
    miracle: "Timely",
    tarot: "2 - The High Priestess",
    attArr: [3, 5, 1, 3, 1, 3, 2, 5],
  },
  {
    styleName: "Mistress",
    miracle: "Fight!",
    tarot: "3 - The Empress",
    attArr: [1, 4, 3, 5, 1, 2, 3, 5],
  },
  {
    styleName: "Kabuto",
    miracle: "Invulnerable",
    tarot: "4 - The Emperor",
    attArr: [2, 4, 1, 4, 3, 5, 1, 3],
  },
  {
    styleName: "Charisma",
    miracle: "Gospel",
    tarot: "5 - The Heirophant",
    attArr: [1, 3, 3, 5, 0, 3, 3, 5],
  },
  {
    styleName: "Mannequin",
    miracle: "Please!",
    tarot: "6 - The Lovers",
    attArr: [1, 3, 3, 5, 2, 5, 1, 3],
  },
  {
    styleName: "Kaze",
    miracle: "Exodus",
    tarot: "7 - The Chariot",
    attArr: [2, 5, 1, 3, 2, 4, 2, 4],
  },
  {
    styleName: "Fate",
    miracle: "Truth",
    tarot: "8 - Strength",
    attArr: [2, 5, 2, 5, 1, 3, 2, 3],
  },
  {
    styleName: "Kuromaku",
    miracle: "Right Hand",
    tarot: "9 - The Hermit",
    attArr: [1, 3, 2, 5, 1, 3, 3, 5],
  },
  {
    styleName: "Exec",
    miracle: "Mergers & Acquisitions",
    tarot: "10 - Wheel of Fortune",
    attArr: [2, 5, 1, 3, 1, 3, 3, 5],
  },
  {
    styleName: "Katana",
    miracle: "Danse Macabre",
    tarot: "11 - Justice",
    attArr: [2, 4, 0, 4, 3, 5, 2, 3],
  },
  {
    styleName: "Kugutsu",
    miracle: "Undercover",
    tarot: "12 - The Hanged Man",
    attArr: [3, 5, 0, 4, 3, 5, 1, 2],
  },
  {
    styleName: "Kage",
    miracle: "Unseen",
    tarot: "13 - Death",
    attArr: [3, 4, 0, 5, 2, 4, 2, 3],
  },
  {
    styleName: "Chakra",
    miracle: "Phoenix",
    tarot: "14 - Temperance",
    attArr: [2, 5, 2, 5, 3, 5, 0, 1],
  },
  {
    styleName: "Legger",
    miracle: "Untouchable",
    tarot: "15 - The Devil",
    attArr: [2, 4, 2, 4, 2, 4, 1, 4],
  },
  {
    styleName: "Kabutowari",
    miracle: "Coup de Grace",
    tarot: "16 - The Tower",
    attArr: [2, 4, 0, 4, 2, 3, 3, 5],
  },
  {
    styleName: "Highlander",
    miracle: "Nemesis",
    tarot: "17 - The Star",
    attArr: [2, 5, 2, 5, 0, 1, 3, 5],
  },
  {
    styleName: "Mayakashi",
    miracle: "Guardian",
    tarot: "18 - The Moon",
    attArr: [3, 5, 3, 5, 0, 2, 1, 4],
  },
  {
    styleName: "Talkie",
    miracle: "Exposure",
    tarot: "19 - The Sun",
    attArr: [2, 5, 3, 5, 1, 3, 1, 3],
  },
  {
    styleName: "Inu",
    miracle: "Banish",
    tarot: "20 - Judgement",
    attArr: [3, 5, 1, 3, 2, 5, 1, 3],
  },
  {
    styleName: "Neuro",
    miracle: "Deus Ex Machina",
    tarot: "21 - The World",
    attArr: [3, 5, 2, 5, 0, 1, 2, 5],
  },
  {
    styleName: "Hiruko",
    miracle: "Mutation",
    tarot: "-1 - The Magician Reversed",
    attArr: [1, 3, 3, 5, 3, 5, 0, 3],
  },
  {
    styleName: "Kurogane",
    miracle: "Masterpiece",
    tarot: "-2 - The High Priestess Reversed",
    attArr: [3, 5, 2, 4, 2, 4, 0, 3],
  },
  {
    styleName: "Ibuki",
    miracle: "Ascend Life",
    tarot: "-4 - The Emperor Reversed",
    attArr: [1, 4, 2, 3, 3, 5, 1, 4],
  },
  {
    styleName: "Arashi",
    miracle: "Breakthrough",
    tarot: "-7 - The Chariot Reversed",
    attArr: [3, 5, 0, 3, 1, 3, 3, 5],
  },
  {
    styleName: "Kagemusha",
    miracle: "Change",
    tarot: "-9 - The Hermit Reversed",
    attArr: [2, 4, 3, 5, 2, 4, 0, 3],
  },
  {
    styleName: "Ayakashi",
    miracle: "Disappear",
    tarot: "-18 - The Moon Reversed",
    attArr: [0, 5, 1, 5, 3, 2, 3, 4],
  },
];